# link any new pages here
nav:
  - Overview:
    - GOID:
      - design/auth-proxy.md
      - oauth2/overview.md
    - FDP:
      - architecture/fdp_architecture.md
      - FI Management:
        - fi_service/fi_onboarding.md
        - fi_service/fi_account_onboarding.md
        - fi_service/fi_transaction.md
      - FI GW:
        - figw_service/figw_datamgmt.md
        - figw_service/figw_data_import.md
      - User Management/Dashboard:
        - userprofile_service/user_mgt.md





# documentation site configurations
site_name: FDS Platform
theme:
  name: 'material'
  feature:
    tabs: true
  palette:
    primary: 'green'
    accent: 'light-green'


extra_javascript:
  - https://unpkg.com/mermaid@8.0.0/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js
  - js/uml.js

extra_css:
  - css/main.css

repo_name: 'fdp/wiki'
repo_url: 'https://localhost/fdp/wiki'
edit_uri: 'edit/master/docs/'

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: sequence
          class: uml-sequence-diagram
        - name: flow
          class: uml-flowchart
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: markdown
          class: markdown
          format: !!python/name:pymdownx.superfences.fence_div_format
